export const IS_LOADING_TIMER = "IS_LOADING_TIMER";

export const GET_TIMER = "GET_TIMER";
export const GET_TIMER_SUCCESS = "GET_TIMER_SUCCESS";
export const GET_TIMER_ERROR = "GET_TIMER_ERROR";

export const START_TIMER = "START_TIMER";
export const START_TIMER_SUCCESS = "START_TIMER_SUCCESS";
export const START_TIMER_ERROR = "START_TIMER_ERROR";

export const STOP_TIMER = "STOP_TIMER";
export const STOP_TIMER_SUCCESS = "STOP_TIMER_SUCCESS";
export const STOP_TIMER_ERROR = "STOP_TIMER_ERROR";
